# Generated by Django 3.0.8 on 2020-07-18 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_comment_listing'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='running',
            field=models.BooleanField(default=True),
        ),
    ]
